name: Baseline Flightdeck (PR annotations)
on:
  pull_request:
    paths: ["**/*.js","**/*.ts","**/*.tsx","**/*.css","**/*.html"]
jobs:
  annotate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9.7.0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm install --frozen-lockfile
      - run: pnpm fetch:features
      - run: pnpm -C packages/core build
      - run: pnpm -C packages/cli build
      - name: Scan
        run: pnpm -C packages/cli start scan --src . --report ./.baseline
      - name: Annotate PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node ./scripts/annotate-pr.mjs
      - uses: actions/upload-artifact@v4
        with:
          name: baseline-report
          path: ./.baseline
