name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack & setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.18.1 --activate

      - name: Install
        run: pnpm install --frozen-lockfile=false

      - name: Build core
        run: pnpm -C packages/core build

      - name: Build CLI
        run: pnpm -C packages/cli build

      - name: Generate features/aliases
        run: pnpm fetch:features

      - name: Run sample scan
        run: node packages/cli/dist/index.js scan --src ./examples/sample-app --report ./examples/sample-app/.baseline --analytics ./examples/sample-app/traffic.csv || true

      - name: Prepare web-report demo data
        run: |
          mkdir -p packages/web-report/public/demo
          cp -f examples/sample-app/.baseline/report.json packages/web-report/public/demo/report.json || echo "{\"summary\":{\"violations\":[],\"warnings\":[],\"achieved\":0,\"coverageBudget\":0},\"features\":{}}" > packages/web-report/public/demo/report.json

      - name: Build web-report
        run: pnpm -C packages/web-report build

      - name: Upload web-report artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-report-dist
          path: packages/web-report/dist
